apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: syslog2azure
  labels:
        app: syslog2azure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog2azure
  template:
    metadata:
      name: syslog2azure
      labels:
        app: syslog2azure      
    spec:
      containers:
      - name: syslog2azure
        image: irom77/syslog2azure:latest
        env:
        - name: SYSLOG_PORT
          value: "6514"
        - name: LOG_TYPE
          value: "SyslogTest"  
        - name: CUSTOMER_ID
          valueFrom:
            configMapKeyRef:
              name: syslog2azure-config
              key: CUSTOMER_ID
        - name: SHARED_KEY
          valueFrom:
            configMapKeyRef:
              name: syslog2azure-config
              key: SHARED_KEY      
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6514
---    
apiVersion: v1
kind: Service
metadata:
  name: syslog2azure
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: syslog2azure
spec:
  type: LoadBalancer
  ports:
  - protocol: UDP
    port: 6514
    name: syslog
  selector:
    app: syslog2azure        